<?php
    /*

        In addition to the functions discussed in previous sections, PHP’s MySQL API comes with a number of ancillary functions 
        that may be used to find out more about the databases and tables on the MySQL server or to obtain server status information.

        Available API Functions
        -----------------------
        mysql_get_server_info()     --> Returns the version number of the MySQL server
        mysql_get_proto_info()      --> Returns the version number of the MySQL protocol
        mysql_get_client_info()     --> Returns the version number of the MySQL client
        mysql_get_host_info()       --> Returns information on the MySQL host
        mysql_thread_id()           --> Returns the thread ID for the current MySQL connection
        mysql_list_dbs()            --> Returns a list of databases available on the MySQL server
        mysql_list_tables()         --> Returns a list of tables available in a speciﬁed MySQL database
        mysql_list_ﬁelds()          --> Returns information about the ﬁelds of a speciﬁed MySQL table
        mysql_stat()                --> Returns status information about the MySQL server
        mysql_info()                --> Returns information about the last executed query
        mysql_db_name()             --> Returns a name of a database from the list generated by mysql_list_dbs()
        mysql_tablename()           --> Returns a name of a table from the list generated by mysql_list_tables()
        mysql_ping()                --> Tests the server connection

        ■ A case study of building an online recruitment application with PHP and MySQL, 
            at http://www.melonfire.com/community/columns/trog/article.php?id=74
        ■ A case study of building a time-and-material tracking system with PHP and MySQL,
            at http://www.melonfire.com/community/columns/trog/article.php?id=92
        ■ A case study of building a document management system with PHP and MySQL, 
            at http://www.melonfire.com/community/columns/trog/article.php?id=64

    */
?>


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Get Database Meta Information</title>
        <basefont face="Arial">
<body>
<?php
    // Open connection
    $connection = mysqli_connect('localhost', 'root', '') or die('Unable to connect!');

    // Get list of available databases
    $dbs_query = mysqli_query($connection, "SHOW DATABASES");
    echo 'Available databases and tables:';
    echo '<ul>';
    while ($db_row = mysqli_fetch_assoc($dbs_query)) {
        $db = $db_row['Database'];
        echo '<li>' . $db . '</li>';

        // For each database, get list of tables within it
        mysqli_select_db($connection, $db);
        $tables_query = mysqli_query($connection, "SHOW TABLES");
        echo '<ul>';
        while ($table_row = mysqli_fetch_row($tables_query)) {
            // Print table name
            echo '<li>' . $table_row[0] . '</li>';
        }
        echo '</ul>';
    }
    echo '</ul>';

    // Get version and host information
    echo "Client version: " . mysqli_get_client_info() . "<br />";
    echo "Server version: " . mysqli_get_server_info($connection) . "<br />";
    echo "Protocol version: " . mysqli_get_proto_info($connection) . "<br />";
    echo "Host: " . mysqli_get_host_info($connection) . "<br />";
    echo "Thread ID: " . mysqli_thread_id($connection) . "<br />";

    // Get server status
    $status = mysqli_stat($connection);
    echo $status;

    // Close connection
    mysqli_close($connection);
?>

</body>
</html>